Update azure-pipelines-DAST.yml for Azure Pipelines

diff --git a/azure-pipelines-DAST.yml b/azure-pipelines-DAST.yml
--- a/azure-pipelines-DAST.yml
+++ b/azure-pipelines-DAST.yml
@@ -36,9 +36,27 @@ stages:
           echo '[INFO] ------------------------------------------------------------------------'
           echo '[INFO] --- RUNNING HMAC SIGNING...'
           echo '[INFO] ------------------------------------------------------------------------'
-          ./veracode-HMAC-Signing.sh $(VID) $(VKEY)
-          http -v --auth-type=veracode_hmac GET "https://api.veracode.com/was/configservice/v1/platform_applications"
+          echo 'Inicio prueba'
+          echo '[INFO] --- CONFIGURING API CREDENTIALS FILE...'
+          echo '[INFO] ------------------------------------------------------------------------'
+          echo '[default]' >> credentials.txt
+          echo 'veracode_api_key_id='$1 >> credentials.txt
+          echo 'veracode_api_key_secret='$2 >> credentials.txt
+          mkdir /home/vsts/.veracode/
+          cp -f credentials.txt /home/vsts/.veracode/credentials
+          chmod 755 /home/vsts/.veracode/credentials
+          echo ''
+
+          #Install Veracode Authentication Library
+          echo '[INFO] ------------------------------------------------------------------------'
+          echo '[INFO ] --- INSTALLING VERACODE AUTHENTICATION LIBRARY...'
+          echo '[INFO] ------------------------------------------------------------------------'
+          pip install veracode-api-signing || echo "[ERROR] There was a problem Installing Veracode Authentication Library..." | exit 1
+          echo 'Fin prueba'
+
+          http --auth-type=veracode_hmac "https://api.veracode.com/was/configservice/v1/platform_applications"
           exit
+#          ./veracode-HMAC-Signing.sh $(VID) $(VKEY)
 
     - task: CmdLine@2
       displayName: DAST Scan KickOff
