Pipeline Scan con custom policy

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -76,12 +76,12 @@ stages:
             echo '[INFO] --- ' $STATUS ' flaws were found.'
             #echo '[INFO] --- Uploading flaws to Azure Work Items...'
             #python Pipeline2AzureWorkItems.py -o oscarrodriguezarias -p verademo -t task -token $(System.AccessToken) -f results.json -bid $(Build.BuildId)
-            exit #STATUS #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
+            exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
           elif [ $STATUS -lt 0 ];
           then
             echo '[INFO] --- Pipeline Scan could not be executed...There are some errors...'
             echo '[INFO] --- ' $STATUS
-            exit $STATUS #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
+            exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
           fi
 
     - task: Veracode@3
