Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -68,7 +68,19 @@ stages:
             echo '[INFO] --- Starting Pipeline Scan execution...'
             java -Dpipeline.debug=true -jar pipeline-scan.jar -vid $(VID) -vkey $(VKEY) --file target/verademo.war --project_name $(System.TeamProject) --project_url $(Build.BuildUri) -so true --issue_details true
             STATUS=${?}            
-            echo '[INFO] --- '$STATUS
+            if [ $STATUS -gt 0 ];
+            then
+              echo '[INFO] --- Pipeline Scan has finished.'
+              echo '[INFO] --- ' $STATUS ' flaws were found!'
+              exit 1
+            elif [ $STATUS -lt 0 ];
+            then
+              echo '[INFO] --- Pipeline Scan couldn't be executed...There are some errors!!'
+              exit 1
+            else
+              echo '[INFO] --- Pipeline Scan has finished.'
+              echo '[INFO] --- No flaws were found!'
+            fi
           else
             echo '[INFO] --- Size Package is greater than 100MB....Pipeline Scan cannot be executed'
           fi
