Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -72,11 +72,12 @@ stages:
             then
               echo '[INFO] --- Pipeline Scan has finished.'
               echo '[INFO] --- ' $STATUS ' flaws were found.'
-              exit 1 #This exit code makes the pipeline break. Remove this line if you need the pipeline continues its execution
+              exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
             elif [ $STATUS -lt 0 ];
             then
               echo '[INFO] --- Pipeline Scan could not be executed...There are some errors...'
-              exit 1
+              echo '[INFO] --- ' $STATUS
+              exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
             fi
           else
             echo '[INFO] --- Size Package is greater than 100MB....Pipeline Scan cannot be executed'
