Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -58,29 +58,22 @@ stages:
       inputs:
         script: |
           echo '[INFO] --- Veracode SAST - Pipeline Scan'
-          SIZE_PACKAGE=$(ls -l target/verademo.war | cut -d " " -f5)
-          if [ $SIZE_PACKAGE -le 100000000 ];
+          echo '[INFO] --- Downloading Pipeline Scan (Latest Version)...'
+          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
+          unzip pipeline-scan-LATEST.zip
+          echo '[INFO] --- Starting Pipeline Scan execution...'
+          java -Dpipeline.debug=true -jar pipeline-scan.jar -vid $(VID) -vkey $(VKEY) --file target/verademo.war --project_name $(System.TeamProject) --project_url $(Build.BuildUri) -so true --issue_details true
+          STATUS=${?}            
+          if [ $STATUS -gt 0 ];
           then
-            echo '[INFO] --- Size Package is less than or equal to 100MB....Pipeline Scan can be executed'
-            echo '[INFO] --- Downloading Pipeline Scan (Latest Version)...'
-            curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
-            unzip pipeline-scan-LATEST.zip
-            echo '[INFO] --- Starting Pipeline Scan execution...'
-            java -Dpipeline.debug=true -jar pipeline-scan.jar -vid $(VID) -vkey $(VKEY) --file target/verademo.war --project_name $(System.TeamProject) --project_url $(Build.BuildUri) -so true --issue_details true
-            STATUS=${?}            
-            if [ $STATUS -gt 0 ];
-            then
-              echo '[INFO] --- Pipeline Scan has finished.'
-              echo '[INFO] --- ' $STATUS ' flaws were found.'
-              exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
-            elif [ $STATUS -lt 0 ];
-            then
-              echo '[INFO] --- Pipeline Scan could not be executed...There are some errors...'
-              echo '[INFO] --- ' $STATUS
-              exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
-            fi
-          else
-            echo '[INFO] --- Size Package is greater than 100MB - ' $STATUS 'bytes....Pipeline Scan cannot be executed'
+            echo '[INFO] --- Pipeline Scan has finished.'
+            echo '[INFO] --- ' $STATUS ' flaws were found.'
+            exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
+          elif [ $STATUS -lt 0 ];
+          then
+            echo '[INFO] --- Pipeline Scan could not be executed...There are some errors...'
+            echo '[INFO] --- ' $STATUS
+            exit 1 #This exit code makes the pipeline breaks. Remove this line if you need the pipeline continues its execution
           fi
 
     - task: Veracode@3
